---
- hosts: "masters, workers"
  remote_user: mcabe
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  
  tasks:
   
   # run apt update
   - name: Running apt update
     ansible.builtin.apt:
       update_cache: yes

   # run apt upgrade
   - name: Running apt upgrade
     ansible.builtin.apt:
       name: "*"
       state: latest

   # run apt update distro
   - name: Running apt dist-upgrade
     ansible.builtin.apt:
       upgrade: dist

   # run apt autormove
   - name: Running apt autoremove
     ansible.builtin.apt:
       autoremove: yes

   - name: Installing application
     ansible.builtin.apt:
       pkg:
         - apt-transport-https
         - ca-certificates
         - curl
         - net-tools
         - conntrack
         - snmp
         - python3-pexpect
         - docker.io
         - sshpass
         - nmap
         - tmux
         - python3-pip
       state: present
       update_cache: yes
       autoremove: yes
